# Generated by Django 4.1.5 on 2023-02-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_category_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentaries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloggerposts', to='blog.blogger'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='category_post', to='blog.category'),
        ),
    ]
