# Generated by Django 4.1.5 on 2023-02-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_coment_blogger_coment_post_coment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogger_comments', to='blog.blogger'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
