# Generated by Django 4.1.5 on 2023-02-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_coment_blogger_alter_coment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='blogger',
        ),
    ]
