# Generated by Django 4.1.5 on 2023-02-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_coment_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='blogger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogger_coments', to='blog.blogger'),
        ),
    ]
