# Generated by Django 4.1.5 on 2023-02-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloggerposts', to='blog.blogger'),
        ),
    ]
